
# H2 + logs SQL
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Pour que data.sql s'exécute correctement avec Boot 2.7
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.datasource.sql-script-encoding=UTF-8

# Propriété métier locale (servira à limiter la liste)
mes-configs.limitDeProduits=5


