spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.datasource.sql-script-encoding=UTF-8
mes-configs.limitDeProduits=3
# laisser Hibernate créer les tables
spring.jpa.hibernate.ddl-auto=create

# très important avec data.sql : d'abord créer le schéma, ensuite insérer les données
spring.jpa.defer-datasource-initialization=true
